### ISSUE TITLE
generate_periodic_mesh usage with points and faces

### ISSUE THREAD

**Issue by dthillaithevan** [nschloe/pygalmesh#165]
Hi,

In cases where it's not possible to define the surfaces mathematically, is it possible to supply the points and triangles (faces) of a surface mesh to the `generate_periodic_mesh` function? I've tried to supply a `.vtu` as the first argument to the function but that didn't seem to work. 

```
import numpy as np
import pygalmesh

#Generate points and faces defining 3D surface mesh
points, verts = ....
cells = [("triangle", faces)]
meshio.write_points_cells('test.vtu',points,cells)

mesh = pygalmesh.generate_periodic_mesh(
    'test.vtu',
    [0, 0, 0, 1, 1, 1],
)
```

Do you know if something like this would be possible?

Thanks!

**Comment by Dee718** [comment]
Ok, thanks. 

Do you know if there is any way to modify the `eval` function used in the periodic Schwarz example to accept a grid of points rather than a single coordinate? 

At the moment the code appears to be looping over the 3D coordinates, `x`, one at a time which is slowing down the code significantly. 

It would be great instead of eval accepting a single `[3,]` coordinate, it could accept a grid of `[n,3]` coordinates (`n` is the total number of points in the domain), then it would be possible to use vectorized functions within `eval` to compute the resulting surface.
